sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bruktekle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bruktekle/react-test npm test

after_success:
  - docker build -t dockerhubdemo1/multi-client ./client
  - docker build -t dockerhubdemo1/multi-nginx ./nginx
  - docker build -t dockerhubdemo1/multi-server ./server
  - docker build -t dockerhubdemo1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockerhubdemo1/multi-client
  - docker push dockerhubdemo1/multi-nginx
  - docker push dockerhubdemo1/multi-server
  - docker push dockerhubdemo1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-525013945828'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
